source 'http://rubygems.org/'

gem 'sinatra'
gem 'haml'
gem 'sass'
gem 'compass'
gem 'compass-960-plugin'
gem 'rack-flash'
gem 'sinatra-content-for', :require => "sinatra/content_for"
gem 'activesupport'
gem 'i18n'
